import base64
import io
from datetime import datetime

import os
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas as pdfcanvas
from reportlab.platypus import (
    BaseDocTemplate,
    PageTemplate,
    Frame,
    NextPageTemplate,
    PageBreak,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable,
    Image as RLImage,
)
from reportlab.graphics.shapes import Drawing, Line, Rect, String, Polygon
from reportlab.graphics.charts.linecharts import HorizontalLineChart
from reportlab.graphics.charts.legends import Legend


# ----------------------------------------------------------------------
# Brand palette -- unified with the ACRO OS logo's ink navy + cyan accent
# ----------------------------------------------------------------------
NAVY = colors.HexColor("#070F1B")        # exact match to the logo artwork background
BLUE = colors.HexColor("#0B5ED7")        # primary accent for content pages
CYAN = colors.HexColor("#4FE0FA")        # brand accent lifted from the logo mark, cover only
LIGHT_BLUE = colors.HexColor("#EAF2FF")
SLATE = colors.HexColor("#5B6472")
LIGHT_GREY = colors.HexColor("#F4F6F9")
BORDER_GREY = colors.HexColor("#D9DEE7")
ACCENT_GREEN = colors.HexColor("#12A150")
ACCENT_AMBER = colors.HexColor("#E08A00")
COVER_MUTED = colors.HexColor("#7C93B8")  # soft slate-blue for cover meta text
WHITE = colors.white


# ----------------------------------------------------------------------
# ACRO OS logo, embedded as base64 so this file has no external asset
# dependency. Replace this constant if the logo artwork ever changes.
# ----------------------------------------------------------------------
_LOGO_PATH = Path(__file__).resolve().parent / "acro_logo.png"
_LOGO_B64 = base64.b64encode(_LOGO_PATH.read_bytes()).decode("utf-8")


def _logo_reader():
    return ImageReader(io.BytesIO(base64.b64decode(_LOGO_B64)))


def _tracked(text, sep=" "):
    """Letter-space a short caps label for a premium, editorial kicker look."""
    return sep.join(list(text.upper()))


class _NumberedCanvas(pdfcanvas.Canvas):
    """Canvas subclass that draws a running header/footer + page numbers,
    and knows to skip the header band on the cover page."""

    def __init__(self, *args, **kwargs):
        pdfcanvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total_pages = len(self._saved_page_states)
        for i, state in enumerate(self._saved_page_states):
            self.__dict__.update(state)
            if i > 0:  # skip decorating the cover page (page 1)
                self._draw_header_footer(i + 1, total_pages)
            pdfcanvas.Canvas.showPage(self)
        pdfcanvas.Canvas.save(self)

    def _draw_header_footer(self, page_num, total_pages):
        width, height = letter

        # Header band
        self.setFillColor(NAVY)
        self.rect(0, height - 0.55 * inch, width, 0.55 * inch, stroke=0, fill=1)
        self.setStrokeColor(BLUE)
        self.setLineWidth(1.4)
        self.line(0, height - 0.55 * inch, width, height - 0.55 * inch)
        self.setFillColor(WHITE)
        self.setFont("Helvetica-Bold", 10)
        self.drawString(0.55 * inch, height - 0.36 * inch,
                         "ADAPTIVE CLOUD RESOURCE ORCHESTRATOR")
        self.setFont("Helvetica", 8.5)
        self.drawRightString(width - 0.55 * inch, height - 0.36 * inch,
                              "Cloud Scheduling Performance Report")

        # Footer
        self.setStrokeColor(BORDER_GREY)
        self.setLineWidth(0.6)
        self.line(0.55 * inch, 0.55 * inch, width - 0.55 * inch, 0.55 * inch)
        self.setFillColor(SLATE)
        self.setFont("Helvetica", 8)
        self.drawString(0.55 * inch, 0.36 * inch,
                         f"Generated {datetime.now().strftime('%d %b %Y, %H:%M')}")
        self.drawCentredString(width / 2, 0.36 * inch, "Generated by ACRO \\u V.1.0")
        self.drawRightString(width - 0.55 * inch, 0.36 * inch,
                              f"Page {page_num - 1} of {total_pages - 1}")


class ReportGenerator:

    def __init__(self):
        styles = getSampleStyleSheet()

        self.cover_kicker_style = ParagraphStyle(
            "CoverKicker", parent=styles["Normal"], fontSize=9.5,
            leading=12, alignment=TA_CENTER, textColor=CYAN,
            fontName="Helvetica-Bold",
        )

        self.cover_title_style = ParagraphStyle(
            "CoverTitle", parent=styles["Heading1"], fontSize=29,
            leading=35, alignment=TA_CENTER, textColor=WHITE,
            fontName="Helvetica-Bold",
        )

        self.cover_subtitle_style = ParagraphStyle(
            "CoverSubtitle", parent=styles["Heading2"], fontSize=11,
            leading=16, alignment=TA_CENTER, textColor=COVER_MUTED,
            fontName="Helvetica",
        )

        self.cover_meta_label_style = ParagraphStyle(
            "CoverMetaLabel", parent=styles["Normal"], fontSize=7.3,
            leading=10, alignment=TA_CENTER, textColor=colors.HexColor("#6E86AC"),
            fontName="Helvetica-Bold",
        )

        self.cover_meta_value_style = ParagraphStyle(
            "CoverMetaValue", parent=styles["Normal"], fontSize=10.5,
            leading=14, alignment=TA_CENTER, textColor=WHITE,
            fontName="Helvetica-Bold",
        )

        self.cover_tag_style = ParagraphStyle(
            "CoverTag", parent=styles["Normal"], fontSize=8.2,
            leading=12, alignment=TA_CENTER, textColor=colors.HexColor("#8FAAD6"),
        )

        self.section_style = ParagraphStyle(
            "Section", parent=styles["Heading2"], fontSize=13,
            textColor=NAVY, spaceBefore=4, spaceAfter=2, fontName="Helvetica-Bold",
        )

        self.section_kicker_style = ParagraphStyle(
            "Kicker", parent=styles["Normal"], fontSize=8.5,
            textColor=BLUE, spaceAfter=2, fontName="Helvetica-Bold",
        )

        self.normal = ParagraphStyle(
            "Body", parent=styles["BodyText"], fontSize=10, leading=15.5,
            textColor=colors.HexColor("#1E2530"), alignment=TA_LEFT,
        )

        self.callout_style = ParagraphStyle(
            "Callout", parent=styles["BodyText"], fontSize=10.3, leading=15.5,
            textColor=NAVY, alignment=TA_LEFT, fontName="Helvetica-Bold",
        )

        self.kpi_label_style = ParagraphStyle(
            "KPILabel", parent=styles["Normal"], fontSize=8.2,
            textColor=SLATE, alignment=TA_CENTER, fontName="Helvetica-Bold",
        )

        self.kpi_value_style = ParagraphStyle(
            "KPIValue", parent=styles["Normal"], fontSize=18,
            textColor=NAVY, alignment=TA_CENTER, fontName="Helvetica-Bold",
            spaceBefore=2,
        )

    # ------------------------------------------------------------------
    # Layout helpers
    # ------------------------------------------------------------------
    def _section(self, story, kicker, title):
        story.append(Spacer(1, 0.14 * inch))
        story.append(Paragraph(kicker.upper(), self.section_kicker_style))
        story.append(Paragraph(title, self.section_style))
        story.append(HRFlowable(width="100%", thickness=1.1, color=BLUE,
                                 spaceBefore=2, spaceAfter=10))

    def _table(self, rows, col_widths=None):
        col_widths = col_widths or [2.6 * inch, 3.4 * inch]
        table = Table(rows, colWidths=col_widths)

        style = [
            ("GRID", (0, 0), (-1, -1), 0.5, BORDER_GREY),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("TEXTCOLOR", (0, 0), (0, -1), NAVY),
            ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#1E2530")),
            ("FONTSIZE", (0, 0), (-1, -1), 9.7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BACKGROUND", (0, 0), (0, -1), LIGHT_BLUE),
        ]
        for i in range(1, len(rows), 2):
            style.append(("BACKGROUND", (1, i), (1, i), LIGHT_GREY))
        table.setStyle(TableStyle(style))
        return table

    def _kpi_cards(self, items):
        """items: list of (label, value, accent_color) tuples."""
        cell_w = 6.9 * inch / len(items)
        cards = []
        for label, value, accent in items:
            inner = Table(
                [[Paragraph(str(value), ParagraphStyle(
                    "v", parent=self.kpi_value_style, textColor=accent,
                    fontSize=self.kpi_value_style.fontSize if len(items) <= 4 else 15))],
                 [Paragraph(label.upper(), self.kpi_label_style)]],
                colWidths=[cell_w - 0.15 * inch],
            )
            inner.setStyle(TableStyle([
                ("TOPPADDING", (0, 0), (-1, 0), 13),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 2),
                ("BOTTOMPADDING", (0, 1), (-1, 1), 13),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("LINEABOVE", (0, 0), (-1, 0), 3, accent),
                ("BOX", (0, 0), (-1, -1), 0.6, BORDER_GREY),
                ("BACKGROUND", (0, 0), (-1, -1), WHITE),
            ]))
            cards.append(inner)

        wrapper = Table([cards], colWidths=[cell_w] * len(items))
        wrapper.setStyle(TableStyle([
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))
        return wrapper

    def _config_chips(self, chips):
        """chips: list of (label, value) tuples rendered as pill-shaped badges."""
        width = 6.9 * inch
        n = len(chips)
        gap = 7
        chip_w = (width - gap * (n - 1)) / n
        height = 44
        d = Drawing(width, height)
        x = 0
        for label, value in chips:
            d.add(Rect(x, 0, chip_w, height, rx=9, ry=9,
                        fillColor=LIGHT_BLUE, strokeColor=BORDER_GREY, strokeWidth=0.6))
            d.add(String(x + chip_w / 2, height - 17, label.upper(), fontSize=6.6,
                          fillColor=SLATE, fontName="Helvetica-Bold", textAnchor="middle"))
            d.add(String(x + chip_w / 2, 11, str(value), fontSize=10.2,
                          fillColor=NAVY, fontName="Helvetica-Bold", textAnchor="middle"))
            x += chip_w + gap
        return d

    def _trend_chart(self, metrics):
        """Line chart of CPU / memory utilization across the sampled ticks,
        set inside a light panel for a more polished, contained look."""
        if len(metrics) < 2:
            return None

        step = max(1, len(metrics) // 30)
        sample = metrics[::step]
        if sample[-1] is not metrics[-1]:
            sample.append(metrics[-1])

        cpu = [m["cpu_utilization"] for m in sample]
        mem = [m["memory_utilization"] for m in sample]

        panel_w, panel_h = 470, 200
        drawing = Drawing(panel_w, panel_h)
        drawing.add(Rect(0, 0, panel_w, panel_h, rx=6, ry=6,
                          fillColor=LIGHT_GREY, strokeColor=BORDER_GREY, strokeWidth=0.7))

        chart = HorizontalLineChart()
        chart.x = 48
        chart.y = 38
        chart.width = 375
        chart.height = 132
        chart.data = [cpu, mem]
        chart.joinedLines = 1
        chart.lines[0].strokeColor = BLUE
        chart.lines[0].strokeWidth = 2.2
        chart.lines[1].strokeColor = ACCENT_GREEN
        chart.lines[1].strokeWidth = 2.2
        chart.lines.symbol = None

        max_val = max(100, max(cpu + mem) + 5)
        chart.valueAxis.valueMin = 0
        chart.valueAxis.valueMax = max_val
        chart.valueAxis.valueStep = max_val / 5
        chart.valueAxis.labelTextFormat = "%d%%"
        chart.valueAxis.labels.fontSize = 7.5
        chart.valueAxis.labels.fillColor = SLATE

        chart.categoryAxis.categoryNames = [str(i) for i in range(len(sample))]
        chart.categoryAxis.labels.fontSize = 0
        chart.categoryAxis.strokeColor = BORDER_GREY
        chart.valueAxis.strokeColor = BORDER_GREY
        chart.valueAxis.gridStrokeColor = colors.HexColor("#E4E9F0")
        chart.valueAxis.visibleGrid = 1

        drawing.add(chart)

        legend = Legend()
        legend.x = 405
        legend.y = 150
        legend.dx = 8
        legend.dy = 8
        legend.fontSize = 8.5
        legend.fontName = "Helvetica"
        legend.columnMaximum = 2
        legend.alignment = "left"
        legend.colorNamePairs = [(BLUE, "CPU %"), (ACCENT_GREEN, "Memory %")]
        drawing.add(legend)

        caption_line = Line(24, 22, 446, 22)
        caption_line.strokeColor = BORDER_GREY
        drawing.add(caption_line)
        drawing.add(String(24, 9, "Sampled simulation ticks (left \\u2192 right = time)",
                            fontSize=7.5, fillColor=SLATE))

        return drawing

    def _callout(self, text):
        """A left-accented 'key takeaway' box to punctuate the narrative summary."""
        box = Table([[Paragraph(text, self.callout_style)]], colWidths=[6.9 * inch])
        box.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BLUE),
            ("LINEBEFORE", (0, 0), (0, -1), 3.5, BLUE),
            ("TOPPADDING", (0, 0), (-1, -1), 12),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
            ("LEFTPADDING", (0, 0), (-1, -1), 14),
            ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ]))
        return box

    # ------------------------------------------------------------------
    # Cover page
    # ------------------------------------------------------------------
    def _cover_background(self, width, height):
        bg = Drawing(width, height)
        bg.add(Rect(0, 0, width, height, fillColor=NAVY, strokeColor=None))
        bg.add(Rect(0, height - 9, width, 9, fillColor=BLUE, strokeColor=None))
        bg.add(Rect(0, 0, width, 9, fillColor=BLUE, strokeColor=None))

        # faint brand watermark: an outline diamond echoing the logo mark
        cx, cy, r = width * 0.83, height * 0.76, 95
        diamond = Polygon(points=[cx, cy + r, cx + r, cy, cx, cy - r, cx - r, cy])
        diamond.fillColor = None
        diamond.strokeColor = CYAN
        diamond.strokeWidth = 1.4
        diamond.strokeOpacity = 0.12
        bg.add(diamond)

        # premium corner brackets
        inset, arm = 30, 26
        for bx, by, dx, dy in [
            (inset, height - inset, 1, -1),
            (width - inset, height - inset, -1, -1),
            (inset, inset, 1, 1),
            (width - inset, inset, -1, 1),
        ]:
            h_line = Line(bx, by, bx + dx * arm, by)
            v_line = Line(bx, by, bx, by + dy * arm)
            for ln in (h_line, v_line):
                ln.strokeColor = CYAN
                ln.strokeWidth = 1.3
                ln.strokeOpacity = 0.55
                bg.add(ln)

        return bg

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------
    def generate(self, filepath, metrics, settings):
        width, height = letter

        doc = BaseDocTemplate(
            filepath,
            pagesize=letter,
            leftMargin=0.55 * inch,
            rightMargin=0.55 * inch,
            topMargin=0.85 * inch,
            bottomMargin=0.75 * inch,
        )

        content_frame = Frame(
            doc.leftMargin, doc.bottomMargin,
            doc.width, doc.height,
            id="content",
        )
        cover_frame = Frame(0, 0, width, height, id="cover", leftPadding=0,
                             rightPadding=0, topPadding=0, bottomPadding=0)

        doc.addPageTemplates([
            PageTemplate(id="Cover", frames=[cover_frame]),
            PageTemplate(id="Content", frames=[content_frame]),
        ])

        story = []

        if not metrics:
            story.append(NextPageTemplate("Content"))
            story.append(Paragraph("No simulation metrics were available.", self.normal))
            doc.build(story, canvasmaker=_NumberedCanvas)
            return

        latest = metrics[-1]
        avg_cpu = round(sum(x["cpu_utilization"] for x in metrics) / len(metrics), 2)
        avg_mem = round(sum(x["memory_utilization"] for x in metrics) / len(metrics), 2)
        peak_wait = max(x["waiting_vms"] for x in metrics)
        sim_id = datetime.now().strftime("SIM-%Y%m%d-%H%M%S")

        # =========================================================
        # PAGE 1 -- Cover
        # =========================================================
        story.append(self._cover_background(width, height))

        story.append(Spacer(1, 1.55 * inch))

        logo_w = 2.85 * inch
        logo_img = RLImage(str(_LOGO_PATH))
        logo_h = logo_w * (logo_img.imageHeight / logo_img.imageWidth)
        logo_img.drawWidth = logo_w
        logo_img.drawHeight = logo_h
        logo_img.hAlign = "CENTER"
        story.append(logo_img)

        story.append(Spacer(1, 0.38 * inch))
        divider = Drawing(0.7 * inch, 2)
        divider.add(Line(0, 0, 0.7 * inch, 0, strokeColor=CYAN, strokeWidth=1.6))
        divider.hAlign = "CENTER"
        story.append(divider)
        story.append(Spacer(1, 0.3 * inch))

        story.append(Paragraph(_tracked("Performance Report"), self.cover_kicker_style))
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph("Cloud Scheduling<br/>Analytics Summary", self.cover_title_style))
        story.append(Spacer(1, 0.16 * inch))
        story.append(Paragraph(
            "A consolidated view of scheduler efficiency, resource utilization,<br/>"
            "and workload throughput across the simulated cluster.",
            self.cover_subtitle_style,
        ))

        story.append(Spacer(1, 0.65 * inch))

        meta_cells = [
            [Paragraph("SIMULATION ID", self.cover_meta_label_style),
             Paragraph("SCHEDULER", self.cover_meta_label_style),
             Paragraph("GENERATED", self.cover_meta_label_style)],
            [Paragraph(sim_id, self.cover_meta_value_style),
             Paragraph(latest["scheduler"], self.cover_meta_value_style),
             Paragraph(datetime.now().strftime("%d %b %Y, %H:%M"), self.cover_meta_value_style)],
        ]
        meta_table = Table(meta_cells, colWidths=[2.1 * inch] * 3)
        meta_table.setStyle(TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LINEBEFORE", (1, 0), (1, -1), 0.7, colors.HexColor("#2A3F63")),
            ("LINEBEFORE", (2, 0), (2, -1), 0.7, colors.HexColor("#2A3F63")),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        meta_table.hAlign = "CENTER"
        story.append(meta_table)

        story.append(Spacer(1, 1.75 * inch))
        story.append(HRFlowable(
            width=2.2 * inch,
            thickness=0.6,
            color=colors.HexColor("#233A5E"),
            hAlign="CENTER",
            spaceAfter=10
        ))
        story.append(Paragraph("Generated by ACRO \\u V.1.0", self.cover_tag_style))
        story.append(Paragraph("Adaptive Cloud Resource Orchestrator \\u2022 Report v1.0",
                                ParagraphStyle("v", parent=self.cover_tag_style, fontSize=7.5,
                                               textColor=colors.HexColor("#5A749E"), spaceBefore=3)))

        story.append(NextPageTemplate("Content"))
        story.append(PageBreak())

        # =========================================================
        # PAGE 2 -- Run configuration, infrastructure & performance
        # =========================================================
        self._section(story, "Run Overview", "Simulation Configuration")
        story.append(self._config_chips([
            ("Simulation ID", sim_id),
            ("Scheduler", latest["scheduler"]),
            ("Scenario", settings.scenario.value),
            ("Load", settings.load_intensity.value),
            ("Max Ticks", str(settings.max_ticks)),
        ]))
        story.append(Spacer(1, 0.05 * inch))

        self._section(story, "Infrastructure", "Cluster Statistics")
        story.append(self._kpi_cards([
            ("Total Hosts", str(latest["total_hosts"]), NAVY),
            ("Total VMs", str(latest["total_vms"]), BLUE),
            ("Completed VMs", str(latest["completed_vms"]), ACCENT_GREEN),
            ("Running VMs", str(latest["running_vms"]), ACCENT_AMBER),
            ("Waiting VMs", str(latest["waiting_vms"]), SLATE),
        ]))

        self._section(story, "Analytics", "Performance Metrics")
        story.append(self._kpi_cards([
            ("Avg CPU Utilization", f"{avg_cpu:.1f}%", BLUE),
            ("Avg Memory Utilization", f"{avg_mem:.1f}%", ACCENT_GREEN),
            ("Avg Waiting Time", f"{latest['average_waiting_time']}t", ACCENT_AMBER),
            ("Peak Wait Queue", str(peak_wait), NAVY),
        ]))

        chart = self._trend_chart(metrics)
        if chart is not None:
            story.append(Spacer(1, 0.2 * inch))
            story.append(Paragraph("Utilization Trend Over Time", ParagraphStyle(
                "chartTitle", parent=self.normal, fontName="Helvetica-Bold", fontSize=9.5,
                textColor=NAVY, spaceAfter=4)))
            story.append(KeepTogether(chart))

        story.append(NextPageTemplate("Content"))
        story.append(PageBreak())

        # =========================================================
        # PAGE 3 -- Narrative summary
        # =========================================================
        self._section(story, "Conclusion", "Simulation Summary")

        story.append(self._callout(
            f"Key takeaway: the <b>{latest['scheduler']}</b> scheduler sustained "
            f"<b>{avg_cpu:.1f}%</b> average CPU and <b>{avg_mem:.1f}%</b> average memory "
            f"utilization while clearing <b>{latest['completed_vms']}</b> of "
            f"<b>{latest['total_vms']}</b> virtual machines."
        ))

        summary = (
            f"The simulation completed successfully over "
            f"<b>{settings.max_ticks}</b> ticks using the "
            f"<b>{latest['scheduler']}</b> scheduler. "
            f"A total of <b>{latest['total_vms']}</b> virtual machines "
            f"were processed across <b>{latest['total_hosts']}</b> compute hosts. "
            f"The average CPU utilization was <b>{avg_cpu:.2f}%</b>, "
            f"average memory utilization was <b>{avg_mem:.2f}%</b>, "
            f"and the average VM waiting time was "
            f"<b>{latest['average_waiting_time']} ticks</b>. "
            f"The peak waiting queue observed during the simulation "
            f"was <b>{peak_wait}</b> virtual machines."
        )
        story.append(Paragraph(summary, self.normal))
        story.append(Spacer(1, 0.35 * inch))

        closing = Table([[Paragraph(
            "<b>Adaptive Cloud Resource Orchestrator (ACRO)</b><br/>"
            "Cloud Scheduling Performance Report \\u2022 Version 1.0",
            ParagraphStyle("footerNote", parent=self.normal, alignment=TA_CENTER,
                            textColor=SLATE, fontSize=9),
        )]], colWidths=[doc.width])
        closing.setStyle(TableStyle([
            ("LINEABOVE", (0, 0), (-1, 0), 1, BORDER_GREY),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(closing)

        doc.build(story, canvasmaker=_NumberedCanvas)